### ISSUE TITLE
Fails when master is checked out

### ISSUE THREAD

**Issue by princed** [realyze/pr-train#10]
`2.2.2`
Stacktrace:

```
fatal: malformed object name master

❌  An error occured. Was there a conflict perhaps?
error Error: fatal: malformed object name master

    at /Users/eugene/.config/yarn/global/node_modules/simple-git/promise.js:21:26
    at Git.<anonymous> (/Users/eugene/.config/yarn/global/node_modules/simple-git/src/git.js:645:18)
    at Function.Git.fail (/Users/eugene/.config/yarn/global/node_modules/simple-git/src/git.js:1478:18)
    at fail (/Users/eugene/.config/yarn/global/node_modules/simple-git/src/git.js:1436:20)
    at /Users/eugene/.config/yarn/global/node_modules/simple-git/src/git.js:1445:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by realyze** [comment]
Ah yes, it does depend on `master` being there (I do some checking there if the branch was already merged into `master` so that we don't push already merged branches). I guess we don't really need that anymore (it was for pr-train 1.0 where you couldn't easily remove branches from the train).

But that should be the only place, methinks.

**Comment by realyze** [comment]
Thanks for the report btw :)
